.TH swatchtime 1
.SH NAME
swatchtime \- displays Swatch Internet Time in a formatted manner

.SH SYNOPSIS
.B swatchtime

.SH DESCRIPTION
SwatchTime is a Python program for displaying the current date and time using
Swatch Internet Time. It provides a set of flags that are useful for a caller
from the CLI or as part of a module for another program; like a Polybar
module. Currently the flags are mostly stable, but may be changed in the
future to be more like date.

.SH OPTIONS
.TP
.BR \-h ", "\-\-help
Display help text and exit

.TP
.BR \-v ", "\-\-verbose
Shows the PID for a few seconds before starting. (default: False)

.SH AUTHOR
Henry Malinowski <malinowski.henry+swatchtime@gmail.com>

.SH REPORTING BUGS
Report issues on GitHub <https://github.com/henry-malinowski/SwatchTime>